#ifndef TEST_WININET_H
#define TEST_WININET_H
#include "windows.h"
typedef void *HINTERNET;
typedef unsigned short INTERNET_PORT;
enum {
    INTERNET_SERVICE_HTTP = 1, INTERNET_FLAG_RELOAD = 2, INTERNET_FLAG_NO_CACHE_WRITE = 4,
    HTTP_QUERY_STATUS_CODE = 8, HTTP_QUERY_FLAG_NUMBER = 16, INTERNET_OPEN_TYPE_DIRECT = 32,
    INTERNET_OPTION_CONNECT_TIMEOUT = 1, INTERNET_OPTION_SEND_TIMEOUT = 2,
    INTERNET_OPTION_RECEIVE_TIMEOUT = 3
};
HINTERNET InternetConnect(HINTERNET, const WCHAR *, INTERNET_PORT, const WCHAR *, const WCHAR *, DWORD, DWORD, size_t);
HINTERNET HttpOpenRequest(HINTERNET, const WCHAR *, const WCHAR *, const WCHAR *, const WCHAR *, const WCHAR **, DWORD, size_t);
BOOL HttpSendRequest(HINTERNET, const WCHAR *, DWORD, LPVOID, DWORD);
BOOL HttpQueryInfo(HINTERNET, DWORD, LPVOID, DWORD *, DWORD *);
BOOL InternetCloseHandle(HINTERNET);
HINTERNET InternetOpen(const WCHAR *, DWORD, const WCHAR *, const WCHAR *, DWORD);
BOOL InternetSetOption(HINTERNET, DWORD, LPVOID, DWORD);
#endif
